// <auto-generated />
using System;
using IDataSphere.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDataSphere.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Repositotys.Log.TL_ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("ExceptionSource")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InnerExceptionMessage")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("TL_ErrorLog");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CourseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CourseDate");

                    b.Property<int>("CourseType")
                        .HasColumnType("int")
                        .HasColumnName("CourseType");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<int>("DanceType")
                        .HasColumnType("int")
                        .HasColumnName("DanceType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("EndTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int")
                        .HasColumnName("MaxParticipants");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PosterUrl");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("StartTime");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("T_Course");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_CourseSignUp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("CardId");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("CourseId");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCancel");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsFinish");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("T_CourseSignUp");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_MyCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("Count");

                    b.Property<int>("CourseType")
                        .HasColumnType("int")
                        .HasColumnName("CourseType");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<int>("DanceType")
                        .HasColumnType("int")
                        .HasColumnName("DanceType");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActivated");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("T_MyCard");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_PersonalCourse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CourseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CourseDate");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<int>("DanceType")
                        .HasColumnType("int")
                        .HasColumnName("DanceType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("EndTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsBooking")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsBooking");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("StartTime");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherId");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("T_PersonalCourse");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_PersonalCourseSignUp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("CardId");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsCancel");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsFinish");

                    b.Property<long>("PersonalCourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("PersonalCourseId");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PersonalCourseId");

                    b.HasIndex("UserId");

                    b.ToTable("T_PersonalCourseSignUp");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("AvatarUrl");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsDisableLogin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDisableLogin");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NickName");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("OpenId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Phone");

                    b.Property<int>("RateCount")
                        .HasColumnType("int")
                        .HasColumnName("RateCount");

                    b.Property<string>("SelfIntroduce")
                        .HasColumnType("longtext")
                        .HasColumnName("SelfIntroduce");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("Sex");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.Property<int>("UserIdentityType")
                        .HasColumnType("int")
                        .HasColumnName("UserIdentityType");

                    b.HasKey("Id");

                    b.ToTable("T_Teacher");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_TeacherDanceType", b =>
                {
                    b.Property<long>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TeacherId");

                    b.Property<int>("DanceType")
                        .HasColumnType("int")
                        .HasColumnName("DanceType");

                    b.Property<long?>("T_TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("TeacherId");

                    b.HasIndex("T_TeacherId");

                    b.ToTable("T_TeacherDanceType");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("AvatarUrl");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedUserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsDisableLogin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDisableLogin");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NickName");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("OpenId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Phone");

                    b.Property<string>("SelfIntroduce")
                        .HasColumnType("longtext")
                        .HasColumnName("SelfIntroduce");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("Sex");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("T_User");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_Course", b =>
                {
                    b.HasOne("Model.Repositotys.Service.T_Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_CourseSignUp", b =>
                {
                    b.HasOne("Model.Repositotys.Service.T_MyCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Repositotys.Service.T_Course", "Course")
                        .WithMany("CourseSignUp")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Repositotys.Service.T_User", "User")
                        .WithMany("CourseSignUps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_MyCard", b =>
                {
                    b.HasOne("Model.Repositotys.Service.T_User", "User")
                        .WithMany("MyCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_PersonalCourse", b =>
                {
                    b.HasOne("Model.Repositotys.Service.T_Teacher", "Teacher")
                        .WithMany("PersonalCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_PersonalCourseSignUp", b =>
                {
                    b.HasOne("Model.Repositotys.Service.T_MyCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Repositotys.Service.T_PersonalCourse", "PersonalCourse")
                        .WithMany("PersonalCourseSignUp")
                        .HasForeignKey("PersonalCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Repositotys.Service.T_User", "User")
                        .WithMany("PersonalCourseSignUps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("PersonalCourse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_TeacherDanceType", b =>
                {
                    b.HasOne("Model.Repositotys.Service.T_Teacher", null)
                        .WithMany("DanceTypes")
                        .HasForeignKey("T_TeacherId");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_Course", b =>
                {
                    b.Navigation("CourseSignUp");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_PersonalCourse", b =>
                {
                    b.Navigation("PersonalCourseSignUp");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_Teacher", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("DanceTypes");

                    b.Navigation("PersonalCourses");
                });

            modelBuilder.Entity("Model.Repositotys.Service.T_User", b =>
                {
                    b.Navigation("CourseSignUps");

                    b.Navigation("MyCards");

                    b.Navigation("PersonalCourseSignUps");
                });
#pragma warning restore 612, 618
        }
    }
}
